### ISSUE TITLE
Redux devTools chrome extension not finding store: 'No store found. Make sure to follow the instructions.'

### ISSUE THREAD

**Issue by TheoMer** [prescottprue/redux-firebasev3#5] opened 2016-08-12 17:47 UTC
OS: Windows 10 Pro
Browser: Version 53.0.2785.57 beta-m (64-bit)
Redux DevTools: 2.4.1

So, I've defined a store enhancer as follows:

`const enhancers = compose(
  window.devToolsExtension ? window.devToolsExtension() : (f) => {f}
);

const createStoreWithFirebase = compose(
    reduxReactFirebase(Firebase_Config, { userProfile: 'users' })
)(createStore);

// Create firebase store
const store = createStoreWithFirebase( rootReducer, defaultState, enhancers );`

but the enhancers, as per createStoreWithFirebase(), is not being picked up.

If I use:

`const store = createStore( rootReducer, defaultState, enhancers );`

then everything works fine.

Also I'm not sure what:

`const store = createStoreWithFirebase( rootReducer, defaultState, enhancers );`

is really supposed to be doing, as no store information is being written to my firebase, which is what  expected to be happening, correct?

What am I overlooking here?

**Comment by prescottprue** [comment] 2016-08-12 17:57
@TheoMer Did you try using [generator-react-firebase](https://github.com/prescottprue/generator-react-firebase)? If you don't want to run the generator itself, the [example with redux](https://github.com/prescottprue/generator-react-firebase/tree/master/examples/react-firebase-redux) uses redux-firebasev3 and should show up in devtools.

#2 Is a similar question, see if that helps.

Not sure what you mean by:

> no store information is being written to my firebase, which is what expected to be happening, correct?

Do you mean the user account should be getting written to Firebase?

**Comment by TheoMer** [comment] 2016-08-12 18:05
@prescottprue Ok, I'll try that.

Yes, I understood createStoreWithFirebase() in literal terms.

**Comment by prescottprue** [comment] 2016-08-17 17:50
@TheoMer Were you able to get it working?

**Comment by TheoMer** [comment] 2016-08-17 19:43
@prescottprue No, that did not work.

I followed the instructions as per [Firebase Deploy](https://github.com/prescottprue/generator-react-firebase/tree/master/examples/react-firebase-redux), but  still I get the error message:

`No store found. Make sure to follow the instructions.`

as can be seen on my test site: [Demo](https://learn-redux.firebaseapp.com/)

**Comment by prescottprue** [comment] 2016-08-18 19:02
I am not seeing that error on the link provided. Is there a repo that you can point me to to test on? Want to reproduce the exact issue you are seeing.

**Comment by TheoMer** [comment] 2016-08-18 20:32
@prescottprue You're 'not seeing that error', as in, a store Is being created in your devTools?!

My project repo is [here](https://github.com/TheoMer/learn-redux)

**Comment by prescottprue** [comment] 2016-08-19 17:21
@TheoMer Yes, my devTools is showing the store and everything is showing in state correctly.

Starting to look at your repo now, will get back to you some time later today. Thanks for pointing out the issue and providing the repo!

**Comment by prescottprue** [comment] 2016-08-19 18:58
I created a [pull request](https://github.com/TheoMer/learn-redux/pull/1) on your repo, and if you don't mind, I might actually end up using this as inspiration for another example. It is a nice simple use of react-snippets!

As for what was causing the store error, It seems like you had two compose calls like so:

``` javascript
// Setup store to be aware by redux dev Tools in chrome
const enhancers = compose(
  window.devToolsExtension ? window.devToolsExtension() : (f) => (f)
);

// Preconfigure firebase store
const createStoreWithFirebase = compose(
    reduxReactFirebase(Firebase_Config, { userProfile: 'users' })
)(createStore);

// Create firebase store
const store = createStoreWithFirebase( rootReducer, defaultState, enhancers );
```

When instead they can be combined to one compose call:

``` javascript
// Preconfigure firebase store
const createStoreWithFirebase = compose(
    window.devToolsExtension ? window.devToolsExtension() : (f) => (f),
    reduxReactFirebase(Firebase_Config, { userProfile: 'users' })
)(createStore);

// Create firebase store
const store = createStoreWithFirebase( rootReducer, defaultState );
```

Going to close this issue since it doesn't seem to be an issue with the library, but I can look into supporting multiple compose functions for the "enhancer" setup you were going for.

**Closed as completed by prescottprue** 2016-08-19 18:58 UTC
Labels: question

**Comment by TheoMer** [comment] 2016-08-19 22:57
@prescottprue All is working now. Many thanks.

Sure, feel free to use it.
